import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navigation";
import ClientWrapper from "./ClientWrapper";
import { Button } from "@/components/ui/button";
import MobileNav from "@/components/shared/MobileNav";
import Navigation from "@/components/shared/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col items-center w-screen min-h-screen ${inter.className} bg-background`}>
        <ClientWrapper>
          <header className="w-screen max-w-screen-lg">
            <MobileNav />
            <Navigation />
          </header>
          <main className="w-screen max-w-screen-lg flex-1">{children}</main>
        </ClientWrapper>
      </body>
    </html>
  );
}
